theme: jekyll-theme-architect
title: Main Contributor for FOOOF Helper Functions
description: This a tutorial on CSP variants and the use of the FOOOF Helper functions. Feel free to download the library expected to be releases by April 2019. 
